/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    posts: Post;
    products: Product;
    categories: Category;
    cities: City;
    'product-options': ProductOption;
    orders: Order;
    'order-fields': OrderField;
    users: User;
    media: Media;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'product-search': ProductSearch;
    'post-search': PostSearch;
    'city-search': CitySearch;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      productOptions: 'product-options';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'product-options': ProductOptionsSelect<false> | ProductOptionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-fields': OrderFieldsSelect<false> | OrderFieldsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'product-search': ProductSearchSelect<false> | ProductSearchSelect<true>;
    'post-search': PostSearchSelect<false> | PostSearchSelect<true>;
    'city-search': CitySearchSelect<false> | CitySearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'zh';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hideSearchInput?: boolean | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'products';
                  value: string | Product;
                } | null)
              | ({
                  relationTo: 'cities';
                  value: string | City;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: string | Category;
                } | null);
            url?: string | null;
            label: string;
            /**
             * 选择链接的样式
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | ColumnBlock
    | GridBlock
    | RowBlock
    | BannerBlock
    | MediaBlock
    | FormBlock
    | SearchBlock
    | ProductCardBlock
    | RecommendationBlock
    | SloganBlock
    | TitleBlock
    | TrendingTagsBlock
    | CallToActionBlock
  )[];
  publishedAt?: string | null;
  slug: string;
  slugLock?: boolean | null;
  meta: {
    /**
     * Keywords that indicate what the page is about. These are used for generating the meta description.
     */
    keywords: {
      keyword: string;
      id?: string | null;
    }[];
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug: string;
  slugLock?: boolean | null;
  meta: {
    /**
     * Keywords that indicate what the page is about. These are used for generating the meta description.
     */
    keywords: {
      keyword: string;
      id?: string | null;
    }[];
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * 为分类选择一个图标
   */
  icon:
    | 'CiAirportSign1'
    | 'CiAlarmOff'
    | 'CiAlarmOn'
    | 'CiAlignBottom'
    | 'CiAlignCenterH'
    | 'CiAlignCenterV'
    | 'CiAlignLeft'
    | 'CiAlignRight'
    | 'CiAlignTop'
    | 'CiApple'
    | 'CiAt'
    | 'CiAvocado'
    | 'CiBacon'
    | 'CiBadgeDollar'
    | 'CiBag1'
    | 'CiBandage'
    | 'CiBank'
    | 'CiBarcode'
    | 'CiBaseball'
    | 'CiBasketball'
    | 'CiBatteryCharging'
    | 'CiBatteryEmpty'
    | 'CiBatteryFull'
    | 'CiBeaker1'
    | 'CiBeerMugFull'
    | 'CiBellOff'
    | 'CiBellOn'
    | 'CiBezier'
    | 'CiBitcoin'
    | 'CiBluetooth'
    | 'CiBookmark'
    | 'CiBookmarkCheck'
    | 'CiBookmarkMinus'
    | 'CiBookmarkPlus'
    | 'CiBookmarkRemove'
    | 'CiBowlNoodles'
    | 'CiBoxList'
    | 'CiBoxes'
    | 'CiBrightnessDown'
    | 'CiBrightnessUp'
    | 'CiBullhorn'
    | 'CiBurger'
    | 'CiCalculator1'
    | 'CiCalculator2'
    | 'CiCalendar'
    | 'CiCalendarDate'
    | 'CiCamera'
    | 'CiChat1'
    | 'CiChat2'
    | 'CiCircleAlert'
    | 'CiCircleCheck'
    | 'CiCircleChevDown'
    | 'CiCircleChevLeft'
    | 'CiCircleChevRight'
    | 'CiCircleChevUp'
    | 'CiCircleInfo'
    | 'CiCircleList'
    | 'CiCircleMinus'
    | 'CiCircleMore'
    | 'CiCirclePlus'
    | 'CiCircleQuestion'
    | 'CiCircleRemove'
    | 'CiClock1'
    | 'CiClock2'
    | 'CiCloud'
    | 'CiCloudDrizzle'
    | 'CiCloudMoon'
    | 'CiCloudOff'
    | 'CiCloudOn'
    | 'CiCloudRainbow'
    | 'CiCloudSun'
    | 'CiCoffeeBean'
    | 'CiCoffeeCup'
    | 'CiCoinInsert'
    | 'CiCoins1'
    | 'CiCompass1'
    | 'CiCreditCard1'
    | 'CiCreditCard2'
    | 'CiCreditCardOff'
    | 'CiCrop'
    | 'CiDark'
    | 'CiDatabase'
    | 'CiDeliveryTruck'
    | 'CiDesktop'
    | 'CiDesktopMouse1'
    | 'CiDesktopMouse2'
    | 'CiDiscount1'
    | 'CiDollar'
    | 'CiDroplet'
    | 'CiDumbbell'
    | 'CiEdit'
    | 'CiEraser'
    | 'CiExport'
    | 'CiFaceFrown'
    | 'CiFaceMeh'
    | 'CiFaceSmile'
    | 'CiFacebook'
    | 'CiFileOff'
    | 'CiFileOn'
    | 'CiFilter'
    | 'CiFlag1'
    | 'CiFloppyDisk'
    | 'CiFolderOff'
    | 'CiFolderOn'
    | 'CiFootball'
    | 'CiForkAndKnife'
    | 'CiFries'
    | 'CiGift'
    | 'CiGlass'
    | 'CiGlobe'
    | 'CiGps'
    | 'CiGrid2H'
    | 'CiGrid2V'
    | 'CiGrid31'
    | 'CiGrid32'
    | 'CiGrid41'
    | 'CiGrid42'
    | 'CiHardDrive'
    | 'CiHashtag'
    | 'CiHeadphones'
    | 'CiHeart'
    | 'CiHome'
    | 'CiHospital1'
    | 'CiHotdog'
    | 'CiIceCream'
    | 'CiImageOff'
    | 'CiImageOn'
    | 'CiImport'
    | 'CiInboxIn'
    | 'CiInboxOut'
    | 'CiIndent'
    | 'CiInstagram'
    | 'CiKeyboard'
    | 'CiLaptop'
    | 'CiLemon'
    | 'CiLight'
    | 'CiLineHeight'
    | 'CiLink'
    | 'CiLinkedin'
    | 'CiLocationArrow1'
    | 'CiLocationOff'
    | 'CiLocationOn'
    | 'CiLock'
    | 'CiLogin'
    | 'CiLogout'
    | 'CiLollipop'
    | 'CiMail'
    | 'CiMap'
    | 'CiMapPin'
    | 'CiMaximize1'
    | 'CiMaximize2'
    | 'CiMedal'
    | 'CiMedicalCase'
    | 'CiMedicalClipboard'
    | 'CiMedicalCross'
    | 'CiMedicalMask'
    | 'CiMemoPad'
    | 'CiMenuBurger'
    | 'CiMenuFries'
    | 'CiMenuKebab'
    | 'CiMicrochip'
    | 'CiMicrophoneOff'
    | 'CiMicrophoneOn'
    | 'CiMinimize1'
    | 'CiMinimize2'
    | 'CiMobile1'
    | 'CiMobile2'
    | 'CiMobile3'
    | 'CiMobile4'
    | 'CiMoneyBill'
    | 'CiMoneyCheck1'
    | 'CiMonitor'
    | 'CiMountain1'
    | 'CiMug1'
    | 'CiMusicNote1'
    | 'CiNoWaitingSign'
    | 'CiPalette'
    | 'CiPaperplane'
    | 'CiParking1'
    | 'CiPassport1'
    | 'CiPause1'
    | 'CiPen'
    | 'CiPenpot'
    | 'CiPercent'
    | 'CiPhone'
    | 'CiPickerEmpty'
    | 'CiPickerHalf'
    | 'CiPill'
    | 'CiPillsBottle1'
    | 'CiPizza'
    | 'CiPlane'
    | 'CiPlay1'
    | 'CiPlug1'
    | 'CiPower'
    | 'CiRainbow'
    | 'CiRead'
    | 'CiReceipt'
    | 'CiRedo'
    | 'CiRepeat'
    | 'CiRollingSuitcase'
    | 'CiRoute'
    | 'CiRouter'
    | 'CiRuler'
    | 'CiSatellite1'
    | 'CiSaveDown1'
    | 'CiSaveDown2'
    | 'CiSaveUp1'
    | 'CiSaveUp2'
    | 'CiSearch'
    | 'CiServer'
    | 'CiSettings'
    | 'CiShare1'
    | 'CiShare2'
    | 'CiShirt'
    | 'CiShop'
    | 'CiShoppingBasket'
    | 'CiShoppingCart'
    | 'CiShoppingTag'
    | 'CiShuffle'
    | 'CiSignpostDuo1'
    | 'CiSignpostL1'
    | 'CiSignpostR1'
    | 'CiSliderHorizontal'
    | 'CiSliderVertical'
    | 'CiSpeaker'
    | 'CiSquareAlert'
    | 'CiSquareCheck'
    | 'CiSquareChevDown'
    | 'CiSquareChevLeft'
    | 'CiSquareChevRight'
    | 'CiSquareChevUp'
    | 'CiSquareInfo'
    | 'CiSquareMinus'
    | 'CiSquareMore'
    | 'CiSquarePlus'
    | 'CiSquareQuestion'
    | 'CiSquareRemove'
    | 'CiStar'
    | 'CiStethoscope'
    | 'CiStickyNote'
    | 'CiStop1'
    | 'CiStopSign1'
    | 'CiStopwatch'
    | 'CiStreamOff'
    | 'CiStreamOn'
    | 'CiSun'
    | 'CiTablets1'
    | 'CiTempHigh'
    | 'CiText'
    | 'CiTextAlignCenter'
    | 'CiTextAlignJustify'
    | 'CiTextAlignLeft'
    | 'CiTextAlignRight'
    | 'CiTimer'
    | 'CiTrash'
    | 'CiTrophy'
    | 'CiTurnL1'
    | 'CiTurnR1'
    | 'CiTwitter'
    | 'CiUmbrella'
    | 'CiUndo'
    | 'CiUnlock'
    | 'CiUnread'
    | 'CiUsb'
    | 'CiUser'
    | 'CiVault'
    | 'CiVial'
    | 'CiVideoOff'
    | 'CiVideoOn'
    | 'CiViewBoard'
    | 'CiViewColumn'
    | 'CiViewList'
    | 'CiViewTable'
    | 'CiViewTimeline'
    | 'CiVirus'
    | 'CiVoicemail'
    | 'CiVolume'
    | 'CiVolumeHigh'
    | 'CiVolumeMute'
    | 'CiWallet'
    | 'CiWarning'
    | 'CiWavePulse1'
    | 'CiWheat'
    | 'CiWifiOff'
    | 'CiWifiOn'
    | 'CiYoutube'
    | 'CiZoomIn'
    | 'CiZoomOut'
    | 'HiAcademicCap'
    | 'HiAdjustments'
    | 'HiAnnotation'
    | 'HiArchive'
    | 'HiArrowCircleDown'
    | 'HiArrowCircleLeft'
    | 'HiArrowCircleRight'
    | 'HiArrowCircleUp'
    | 'HiArrowDown'
    | 'HiArrowLeft'
    | 'HiArrowNarrowDown'
    | 'HiArrowNarrowLeft'
    | 'HiArrowNarrowRight'
    | 'HiArrowNarrowUp'
    | 'HiArrowRight'
    | 'HiArrowSmDown'
    | 'HiArrowSmLeft'
    | 'HiArrowSmRight'
    | 'HiArrowSmUp'
    | 'HiArrowUp'
    | 'HiArrowsExpand'
    | 'HiAtSymbol'
    | 'HiBackspace'
    | 'HiBadgeCheck'
    | 'HiBan'
    | 'HiBeaker'
    | 'HiBell'
    | 'HiBookOpen'
    | 'HiBookmark'
    | 'HiBookmarkAlt'
    | 'HiBriefcase'
    | 'HiCake'
    | 'HiCalculator'
    | 'HiCalendar'
    | 'HiCamera'
    | 'HiCash'
    | 'HiChartBar'
    | 'HiChartPie'
    | 'HiChartSquareBar'
    | 'HiChat'
    | 'HiChatAlt'
    | 'HiChatAlt2'
    | 'HiCheck'
    | 'HiCheckCircle'
    | 'HiChevronDoubleDown'
    | 'HiChevronDoubleLeft'
    | 'HiChevronDoubleRight'
    | 'HiChevronDoubleUp'
    | 'HiChevronDown'
    | 'HiChevronLeft'
    | 'HiChevronRight'
    | 'HiChevronUp'
    | 'HiChip'
    | 'HiClipboard'
    | 'HiClipboardCheck'
    | 'HiClipboardCopy'
    | 'HiClipboardList'
    | 'HiClock'
    | 'HiCloud'
    | 'HiCloudDownload'
    | 'HiCloudUpload'
    | 'HiCode'
    | 'HiCog'
    | 'HiCollection'
    | 'HiColorSwatch'
    | 'HiCreditCard'
    | 'HiCube'
    | 'HiCubeTransparent'
    | 'HiCurrencyBangladeshi'
    | 'HiCurrencyDollar'
    | 'HiCurrencyEuro'
    | 'HiCurrencyPound'
    | 'HiCurrencyRupee'
    | 'HiCurrencyYen'
    | 'HiCursorClick'
    | 'HiDatabase'
    | 'HiDesktopComputer'
    | 'HiDeviceMobile'
    | 'HiDeviceTablet'
    | 'HiDocument'
    | 'HiDocumentAdd'
    | 'HiDocumentDownload'
    | 'HiDocumentDuplicate'
    | 'HiDocumentRemove'
    | 'HiDocumentReport'
    | 'HiDocumentSearch'
    | 'HiDocumentText'
    | 'HiDotsCircleHorizontal'
    | 'HiDotsHorizontal'
    | 'HiDotsVertical'
    | 'HiDownload'
    | 'HiDuplicate'
    | 'HiEmojiHappy'
    | 'HiEmojiSad'
    | 'HiExclamation'
    | 'HiExclamationCircle'
    | 'HiExternalLink'
    | 'HiEye'
    | 'HiEyeOff'
    | 'HiFastForward'
    | 'HiFilm'
    | 'HiFilter'
    | 'HiFingerPrint'
    | 'HiFire'
    | 'HiFlag'
    | 'HiFolder'
    | 'HiFolderAdd'
    | 'HiFolderDownload'
    | 'HiFolderOpen'
    | 'HiFolderRemove'
    | 'HiGift'
    | 'HiGlobe'
    | 'HiGlobeAlt'
    | 'HiHand'
    | 'HiHashtag'
    | 'HiHeart'
    | 'HiHome'
    | 'HiIdentification'
    | 'HiInbox'
    | 'HiInboxIn'
    | 'HiInformationCircle'
    | 'HiKey'
    | 'HiLibrary'
    | 'HiLightBulb'
    | 'HiLightningBolt'
    | 'HiLink'
    | 'HiLocationMarker'
    | 'HiLockClosed'
    | 'HiLockOpen'
    | 'HiLogin'
    | 'HiLogout'
    | 'HiMail'
    | 'HiMailOpen'
    | 'HiMap'
    | 'HiMenu'
    | 'HiMenuAlt1'
    | 'HiMenuAlt2'
    | 'HiMenuAlt3'
    | 'HiMenuAlt4'
    | 'HiMicrophone'
    | 'HiMinus'
    | 'HiMinusCircle'
    | 'HiMinusSm'
    | 'HiMoon'
    | 'HiMusicNote'
    | 'HiNewspaper'
    | 'HiOfficeBuilding'
    | 'HiOutlineAcademicCap'
    | 'HiOutlineAdjustments'
    | 'HiOutlineAnnotation'
    | 'HiOutlineArchive'
    | 'HiOutlineArrowCircleDown'
    | 'HiOutlineArrowCircleLeft'
    | 'HiOutlineArrowCircleRight'
    | 'HiOutlineArrowCircleUp'
    | 'HiOutlineArrowDown'
    | 'HiOutlineArrowLeft'
    | 'HiOutlineArrowNarrowDown'
    | 'HiOutlineArrowNarrowLeft'
    | 'HiOutlineArrowNarrowRight'
    | 'HiOutlineArrowNarrowUp'
    | 'HiOutlineArrowRight'
    | 'HiOutlineArrowSmDown'
    | 'HiOutlineArrowSmLeft'
    | 'HiOutlineArrowSmRight'
    | 'HiOutlineArrowSmUp'
    | 'HiOutlineArrowUp'
    | 'HiOutlineArrowsExpand'
    | 'HiOutlineAtSymbol'
    | 'HiOutlineBackspace'
    | 'HiOutlineBadgeCheck'
    | 'HiOutlineBan'
    | 'HiOutlineBeaker'
    | 'HiOutlineBell'
    | 'HiOutlineBookOpen'
    | 'HiOutlineBookmark'
    | 'HiOutlineBookmarkAlt'
    | 'HiOutlineBriefcase'
    | 'HiOutlineCake'
    | 'HiOutlineCalculator'
    | 'HiOutlineCalendar'
    | 'HiOutlineCamera'
    | 'HiOutlineCash'
    | 'HiOutlineChartBar'
    | 'HiOutlineChartPie'
    | 'HiOutlineChartSquareBar'
    | 'HiOutlineChat'
    | 'HiOutlineChatAlt'
    | 'HiOutlineChatAlt2'
    | 'HiOutlineCheck'
    | 'HiOutlineCheckCircle'
    | 'HiOutlineChevronDoubleDown'
    | 'HiOutlineChevronDoubleLeft'
    | 'HiOutlineChevronDoubleRight'
    | 'HiOutlineChevronDoubleUp'
    | 'HiOutlineChevronDown'
    | 'HiOutlineChevronLeft'
    | 'HiOutlineChevronRight'
    | 'HiOutlineChevronUp'
    | 'HiOutlineChip'
    | 'HiOutlineClipboard'
    | 'HiOutlineClipboardCheck'
    | 'HiOutlineClipboardCopy'
    | 'HiOutlineClipboardList'
    | 'HiOutlineClock'
    | 'HiOutlineCloud'
    | 'HiOutlineCloudDownload'
    | 'HiOutlineCloudUpload'
    | 'HiOutlineCode'
    | 'HiOutlineCog'
    | 'HiOutlineCollection'
    | 'HiOutlineColorSwatch'
    | 'HiOutlineCreditCard'
    | 'HiOutlineCube'
    | 'HiOutlineCubeTransparent'
    | 'HiOutlineCurrencyBangladeshi'
    | 'HiOutlineCurrencyDollar'
    | 'HiOutlineCurrencyEuro'
    | 'HiOutlineCurrencyPound'
    | 'HiOutlineCurrencyRupee'
    | 'HiOutlineCurrencyYen'
    | 'HiOutlineCursorClick'
    | 'HiOutlineDatabase'
    | 'HiOutlineDesktopComputer'
    | 'HiOutlineDeviceMobile'
    | 'HiOutlineDeviceTablet'
    | 'HiOutlineDocument'
    | 'HiOutlineDocumentAdd'
    | 'HiOutlineDocumentDownload'
    | 'HiOutlineDocumentDuplicate'
    | 'HiOutlineDocumentRemove'
    | 'HiOutlineDocumentReport'
    | 'HiOutlineDocumentSearch'
    | 'HiOutlineDocumentText'
    | 'HiOutlineDotsCircleHorizontal'
    | 'HiOutlineDotsHorizontal'
    | 'HiOutlineDotsVertical'
    | 'HiOutlineDownload'
    | 'HiOutlineDuplicate'
    | 'HiOutlineEmojiHappy'
    | 'HiOutlineEmojiSad'
    | 'HiOutlineExclamation'
    | 'HiOutlineExclamationCircle'
    | 'HiOutlineExternalLink'
    | 'HiOutlineEye'
    | 'HiOutlineEyeOff'
    | 'HiOutlineFastForward'
    | 'HiOutlineFilm'
    | 'HiOutlineFilter'
    | 'HiOutlineFingerPrint'
    | 'HiOutlineFire'
    | 'HiOutlineFlag'
    | 'HiOutlineFolder'
    | 'HiOutlineFolderAdd'
    | 'HiOutlineFolderDownload'
    | 'HiOutlineFolderOpen'
    | 'HiOutlineFolderRemove'
    | 'HiOutlineGift'
    | 'HiOutlineGlobe'
    | 'HiOutlineGlobeAlt'
    | 'HiOutlineHand'
    | 'HiOutlineHashtag'
    | 'HiOutlineHeart'
    | 'HiOutlineHome'
    | 'HiOutlineIdentification'
    | 'HiOutlineInbox'
    | 'HiOutlineInboxIn'
    | 'HiOutlineInformationCircle'
    | 'HiOutlineKey'
    | 'HiOutlineLibrary'
    | 'HiOutlineLightBulb'
    | 'HiOutlineLightningBolt'
    | 'HiOutlineLink'
    | 'HiOutlineLocationMarker'
    | 'HiOutlineLockClosed'
    | 'HiOutlineLockOpen'
    | 'HiOutlineLogin'
    | 'HiOutlineLogout'
    | 'HiOutlineMail'
    | 'HiOutlineMailOpen'
    | 'HiOutlineMap'
    | 'HiOutlineMenu'
    | 'HiOutlineMenuAlt1'
    | 'HiOutlineMenuAlt2'
    | 'HiOutlineMenuAlt3'
    | 'HiOutlineMenuAlt4'
    | 'HiOutlineMicrophone'
    | 'HiOutlineMinus'
    | 'HiOutlineMinusCircle'
    | 'HiOutlineMinusSm'
    | 'HiOutlineMoon'
    | 'HiOutlineMusicNote'
    | 'HiOutlineNewspaper'
    | 'HiOutlineOfficeBuilding'
    | 'HiOutlinePaperAirplane'
    | 'HiOutlinePaperClip'
    | 'HiOutlinePause'
    | 'HiOutlinePencil'
    | 'HiOutlinePencilAlt'
    | 'HiOutlinePhone'
    | 'HiOutlinePhoneIncoming'
    | 'HiOutlinePhoneMissedCall'
    | 'HiOutlinePhoneOutgoing'
    | 'HiOutlinePhotograph'
    | 'HiOutlinePlay'
    | 'HiOutlinePlus'
    | 'HiOutlinePlusCircle'
    | 'HiOutlinePlusSm'
    | 'HiOutlinePresentationChartBar'
    | 'HiOutlinePresentationChartLine'
    | 'HiOutlinePrinter'
    | 'HiOutlinePuzzle'
    | 'HiOutlineQrcode'
    | 'HiOutlineQuestionMarkCircle'
    | 'HiOutlineReceiptRefund'
    | 'HiOutlineReceiptTax'
    | 'HiOutlineRefresh'
    | 'HiOutlineReply'
    | 'HiOutlineRewind'
    | 'HiOutlineRss'
    | 'HiOutlineSave'
    | 'HiOutlineSaveAs'
    | 'HiOutlineScale'
    | 'HiOutlineScissors'
    | 'HiOutlineSearch'
    | 'HiOutlineSearchCircle'
    | 'HiOutlineSelector'
    | 'HiOutlineServer'
    | 'HiOutlineShare'
    | 'HiOutlineShieldCheck'
    | 'HiOutlineShieldExclamation'
    | 'HiOutlineShoppingBag'
    | 'HiOutlineShoppingCart'
    | 'HiOutlineSortAscending'
    | 'HiOutlineSortDescending'
    | 'HiOutlineSparkles'
    | 'HiOutlineSpeakerphone'
    | 'HiOutlineStar'
    | 'HiOutlineStatusOffline'
    | 'HiOutlineStatusOnline'
    | 'HiOutlineStop'
    | 'HiOutlineSun'
    | 'HiOutlineSupport'
    | 'HiOutlineSwitchHorizontal'
    | 'HiOutlineSwitchVertical'
    | 'HiOutlineTable'
    | 'HiOutlineTag'
    | 'HiOutlineTemplate'
    | 'HiOutlineTerminal'
    | 'HiOutlineThumbDown'
    | 'HiOutlineThumbUp'
    | 'HiOutlineTicket'
    | 'HiOutlineTranslate'
    | 'HiOutlineTrash'
    | 'HiOutlineTrendingDown'
    | 'HiOutlineTrendingUp'
    | 'HiOutlineTruck'
    | 'HiOutlineUpload'
    | 'HiOutlineUser'
    | 'HiOutlineUserAdd'
    | 'HiOutlineUserCircle'
    | 'HiOutlineUserGroup'
    | 'HiOutlineUserRemove'
    | 'HiOutlineUsers'
    | 'HiOutlineVariable'
    | 'HiOutlineVideoCamera'
    | 'HiOutlineViewBoards'
    | 'HiOutlineViewGrid'
    | 'HiOutlineViewGridAdd'
    | 'HiOutlineViewList'
    | 'HiOutlineVolumeOff'
    | 'HiOutlineVolumeUp'
    | 'HiOutlineWifi'
    | 'HiOutlineX'
    | 'HiOutlineXCircle'
    | 'HiOutlineZoomIn'
    | 'HiOutlineZoomOut'
    | 'HiPaperAirplane'
    | 'HiPaperClip'
    | 'HiPause'
    | 'HiPencil'
    | 'HiPencilAlt'
    | 'HiPhone'
    | 'HiPhoneIncoming'
    | 'HiPhoneMissedCall'
    | 'HiPhoneOutgoing'
    | 'HiPhotograph'
    | 'HiPlay'
    | 'HiPlus'
    | 'HiPlusCircle'
    | 'HiPlusSm'
    | 'HiPresentationChartBar'
    | 'HiPresentationChartLine'
    | 'HiPrinter'
    | 'HiPuzzle'
    | 'HiQrcode'
    | 'HiQuestionMarkCircle'
    | 'HiReceiptRefund'
    | 'HiReceiptTax'
    | 'HiRefresh'
    | 'HiReply'
    | 'HiRewind'
    | 'HiRss'
    | 'HiSave'
    | 'HiSaveAs'
    | 'HiScale'
    | 'HiScissors'
    | 'HiSearch'
    | 'HiSearchCircle'
    | 'HiSelector'
    | 'HiServer'
    | 'HiShare'
    | 'HiShieldCheck'
    | 'HiShieldExclamation'
    | 'HiShoppingBag'
    | 'HiShoppingCart'
    | 'HiSortAscending'
    | 'HiSortDescending'
    | 'HiSparkles'
    | 'HiSpeakerphone'
    | 'HiStar'
    | 'HiStatusOffline'
    | 'HiStatusOnline'
    | 'HiStop'
    | 'HiSun'
    | 'HiSupport'
    | 'HiSwitchHorizontal'
    | 'HiSwitchVertical'
    | 'HiTable'
    | 'HiTag'
    | 'HiTemplate'
    | 'HiTerminal'
    | 'HiThumbDown'
    | 'HiThumbUp'
    | 'HiTicket'
    | 'HiTranslate'
    | 'HiTrash'
    | 'HiTrendingDown'
    | 'HiTrendingUp'
    | 'HiTruck'
    | 'HiUpload'
    | 'HiUser'
    | 'HiUserAdd'
    | 'HiUserCircle'
    | 'HiUserGroup'
    | 'HiUserRemove'
    | 'HiUsers'
    | 'HiVariable'
    | 'HiVideoCamera'
    | 'HiViewBoards'
    | 'HiViewGrid'
    | 'HiViewGridAdd'
    | 'HiViewList'
    | 'HiVolumeOff'
    | 'HiVolumeUp'
    | 'HiWifi'
    | 'HiX'
    | 'HiXCircle'
    | 'HiZoomIn'
    | 'HiZoomOut';
  slug: string;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * 自动计算的最低价格
   */
  lowestPrice?: number | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  categories?: (string | Category)[] | null;
  summary?: string | null;
  aboutThisTour: {
    cancellation: number;
    duration: number;
    disabledFriendly?: boolean | null;
    skipTicketLine?: boolean | null;
  };
  /**
   * 添加产品亮点或重要注意事项
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  importantInfo?:
    | {
        title: string;
        content?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  city?: (string | null) | City;
  productOptions?: {
    docs?: (string | ProductOption)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  slug: string;
  slugLock?: boolean | null;
  meta: {
    /**
     * Keywords that indicate what the page is about. These are used for generating the meta description.
     */
    keywords: {
      keyword: string;
      id?: string | null;
    }[];
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  title: string;
  image: string | Media;
  /**
   * 设置城市的主题颜色
   */
  themeColor: string;
  slug: string;
  slugLock?: boolean | null;
  meta: {
    /**
     * Keywords that indicate what the page is about. These are used for generating the meta description.
     */
    keywords: {
      keyword: string;
      id?: string | null;
    }[];
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-options".
 */
export interface ProductOption {
  id: string;
  useAsTitle?: string | null;
  product: string | Product;
  title: string;
  summary?: string | null;
  applicableCustomers?: ('Adult' | 'Youth' | 'Children' | 'Senior')[] | null;
  /**
   * 选择预订该产品时需要填写的表单
   */
  requiredInfo?: (string | OrderField)[] | null;
  /**
   * 配置不同时期的可用时间
   */
  availableDate: {
    /**
     * 选择适用的月份
     */
    months: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12')[];
    /**
     * 选择适用的星期
     */
    days: ('1' | '2' | '3' | '4' | '5' | '6' | '7')[];
    available?: boolean | null;
    /**
     * 添加可选的时间段，如"8:00AM~12:00PM"
     */
    timeRange?:
      | {
          time: string;
          id?: string | null;
        }[]
      | null;
    price?: {
      Adult?: number | null;
      Youth?: number | null;
      Children?: number | null;
      Senior?: number | null;
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-fields".
 */
export interface OrderField {
  id: string;
  name: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'payment';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnBlock".
 */
export interface ColumnBlock {
  alignment?: ('start' | 'center' | 'end') | null;
  spacing?: ('small' | 'medium' | 'large') | null;
  blocks?:
    | (
        | BannerBlock
        | MediaBlock
        | FormBlock
        | SearchBlock
        | ProductCardBlock
        | RecommendationBlock
        | SloganBlock
        | TitleBlock
        | TrendingTagsBlock
        | CallToActionBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columnBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bannerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SearchBlock".
 */
export interface SearchBlock {
  title?: string | null;
  subtitle?: string | null;
  placeholder?: string | null;
  trendingSearches?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'cities';
                value: string | City;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'searchBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCardBlock".
 */
export interface ProductCardBlock {
  products: (string | ProductSearch)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'productCardBlock';
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-search".
 */
export interface ProductSearch {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'products';
    value: string | Product;
  };
  categories?:
    | {
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  summary?: string | null;
  image?: {
    url?: string | null;
    alt?: string | null;
  };
  slug?: string | null;
  city?: {
    title?: string | null;
    themeColor?: string | null;
  };
  aboutThisTour?: {
    cancellation?: number | null;
    duration?: number | null;
    disabledFriendly?: boolean | null;
    skipTicketLine?: boolean | null;
  };
  lowestPrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendationBlock".
 */
export interface RecommendationBlock {
  mode: 'auto' | 'manual';
  selectedProducts?: (string | ProductSearch)[] | null;
  filterType?: ('all' | 'city' | 'category') | null;
  city?: (string | null) | City;
  category?: (string | null) | Category;
  limit?: number | null;
  enableLoadMore?: ('none' | 'click' | 'auto') | null;
  loadMoreLimit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recommendationBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sloganBlock".
 */
export interface SloganBlock {
  keywords?:
    | {
        text: string;
        isLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'cities';
                value: string | City;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          /**
           * 选择链接的样式
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sloganBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "titleBlock".
 */
export interface TitleBlock {
  title: string;
  subtitle?: string | null;
  variant?: ('center' | 'left' | 'right') | null;
  color?: ('foreground' | 'primary' | 'secondary' | 'muted' | 'mutedForeground') | null;
  size?: ('xs' | 'sm' | 'default' | 'lg' | 'xl') | null;
  textTransform?: ('uppercase' | 'lowercase' | 'capitalize' | 'normal') | null;
  weight?: ('normal' | 'medium' | 'bold') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'titleBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trendingTagsBlock".
 */
export interface TrendingTagsBlock {
  tags: {
    text: string;
    isLink?: boolean | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null)
        | ({
            relationTo: 'products';
            value: string | Product;
          } | null)
        | ({
            relationTo: 'cities';
            value: string | City;
          } | null)
        | ({
            relationTo: 'categories';
            value: string | Category;
          } | null);
      url?: string | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'trendingTagsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callToActionBlock".
 */
export interface CallToActionBlock {
  title: string;
  description: string;
  buttonText: string;
  icon:
    | 'CiAirportSign1'
    | 'CiAlarmOff'
    | 'CiAlarmOn'
    | 'CiAlignBottom'
    | 'CiAlignCenterH'
    | 'CiAlignCenterV'
    | 'CiAlignLeft'
    | 'CiAlignRight'
    | 'CiAlignTop'
    | 'CiApple'
    | 'CiAt'
    | 'CiAvocado'
    | 'CiBacon'
    | 'CiBadgeDollar'
    | 'CiBag1'
    | 'CiBandage'
    | 'CiBank'
    | 'CiBarcode'
    | 'CiBaseball'
    | 'CiBasketball'
    | 'CiBatteryCharging'
    | 'CiBatteryEmpty'
    | 'CiBatteryFull'
    | 'CiBeaker1'
    | 'CiBeerMugFull'
    | 'CiBellOff'
    | 'CiBellOn'
    | 'CiBezier'
    | 'CiBitcoin'
    | 'CiBluetooth'
    | 'CiBookmark'
    | 'CiBookmarkCheck'
    | 'CiBookmarkMinus'
    | 'CiBookmarkPlus'
    | 'CiBookmarkRemove'
    | 'CiBowlNoodles'
    | 'CiBoxList'
    | 'CiBoxes'
    | 'CiBrightnessDown'
    | 'CiBrightnessUp'
    | 'CiBullhorn'
    | 'CiBurger'
    | 'CiCalculator1'
    | 'CiCalculator2'
    | 'CiCalendar'
    | 'CiCalendarDate'
    | 'CiCamera'
    | 'CiChat1'
    | 'CiChat2'
    | 'CiCircleAlert'
    | 'CiCircleCheck'
    | 'CiCircleChevDown'
    | 'CiCircleChevLeft'
    | 'CiCircleChevRight'
    | 'CiCircleChevUp'
    | 'CiCircleInfo'
    | 'CiCircleList'
    | 'CiCircleMinus'
    | 'CiCircleMore'
    | 'CiCirclePlus'
    | 'CiCircleQuestion'
    | 'CiCircleRemove'
    | 'CiClock1'
    | 'CiClock2'
    | 'CiCloud'
    | 'CiCloudDrizzle'
    | 'CiCloudMoon'
    | 'CiCloudOff'
    | 'CiCloudOn'
    | 'CiCloudRainbow'
    | 'CiCloudSun'
    | 'CiCoffeeBean'
    | 'CiCoffeeCup'
    | 'CiCoinInsert'
    | 'CiCoins1'
    | 'CiCompass1'
    | 'CiCreditCard1'
    | 'CiCreditCard2'
    | 'CiCreditCardOff'
    | 'CiCrop'
    | 'CiDark'
    | 'CiDatabase'
    | 'CiDeliveryTruck'
    | 'CiDesktop'
    | 'CiDesktopMouse1'
    | 'CiDesktopMouse2'
    | 'CiDiscount1'
    | 'CiDollar'
    | 'CiDroplet'
    | 'CiDumbbell'
    | 'CiEdit'
    | 'CiEraser'
    | 'CiExport'
    | 'CiFaceFrown'
    | 'CiFaceMeh'
    | 'CiFaceSmile'
    | 'CiFacebook'
    | 'CiFileOff'
    | 'CiFileOn'
    | 'CiFilter'
    | 'CiFlag1'
    | 'CiFloppyDisk'
    | 'CiFolderOff'
    | 'CiFolderOn'
    | 'CiFootball'
    | 'CiForkAndKnife'
    | 'CiFries'
    | 'CiGift'
    | 'CiGlass'
    | 'CiGlobe'
    | 'CiGps'
    | 'CiGrid2H'
    | 'CiGrid2V'
    | 'CiGrid31'
    | 'CiGrid32'
    | 'CiGrid41'
    | 'CiGrid42'
    | 'CiHardDrive'
    | 'CiHashtag'
    | 'CiHeadphones'
    | 'CiHeart'
    | 'CiHome'
    | 'CiHospital1'
    | 'CiHotdog'
    | 'CiIceCream'
    | 'CiImageOff'
    | 'CiImageOn'
    | 'CiImport'
    | 'CiInboxIn'
    | 'CiInboxOut'
    | 'CiIndent'
    | 'CiInstagram'
    | 'CiKeyboard'
    | 'CiLaptop'
    | 'CiLemon'
    | 'CiLight'
    | 'CiLineHeight'
    | 'CiLink'
    | 'CiLinkedin'
    | 'CiLocationArrow1'
    | 'CiLocationOff'
    | 'CiLocationOn'
    | 'CiLock'
    | 'CiLogin'
    | 'CiLogout'
    | 'CiLollipop'
    | 'CiMail'
    | 'CiMap'
    | 'CiMapPin'
    | 'CiMaximize1'
    | 'CiMaximize2'
    | 'CiMedal'
    | 'CiMedicalCase'
    | 'CiMedicalClipboard'
    | 'CiMedicalCross'
    | 'CiMedicalMask'
    | 'CiMemoPad'
    | 'CiMenuBurger'
    | 'CiMenuFries'
    | 'CiMenuKebab'
    | 'CiMicrochip'
    | 'CiMicrophoneOff'
    | 'CiMicrophoneOn'
    | 'CiMinimize1'
    | 'CiMinimize2'
    | 'CiMobile1'
    | 'CiMobile2'
    | 'CiMobile3'
    | 'CiMobile4'
    | 'CiMoneyBill'
    | 'CiMoneyCheck1'
    | 'CiMonitor'
    | 'CiMountain1'
    | 'CiMug1'
    | 'CiMusicNote1'
    | 'CiNoWaitingSign'
    | 'CiPalette'
    | 'CiPaperplane'
    | 'CiParking1'
    | 'CiPassport1'
    | 'CiPause1'
    | 'CiPen'
    | 'CiPenpot'
    | 'CiPercent'
    | 'CiPhone'
    | 'CiPickerEmpty'
    | 'CiPickerHalf'
    | 'CiPill'
    | 'CiPillsBottle1'
    | 'CiPizza'
    | 'CiPlane'
    | 'CiPlay1'
    | 'CiPlug1'
    | 'CiPower'
    | 'CiRainbow'
    | 'CiRead'
    | 'CiReceipt'
    | 'CiRedo'
    | 'CiRepeat'
    | 'CiRollingSuitcase'
    | 'CiRoute'
    | 'CiRouter'
    | 'CiRuler'
    | 'CiSatellite1'
    | 'CiSaveDown1'
    | 'CiSaveDown2'
    | 'CiSaveUp1'
    | 'CiSaveUp2'
    | 'CiSearch'
    | 'CiServer'
    | 'CiSettings'
    | 'CiShare1'
    | 'CiShare2'
    | 'CiShirt'
    | 'CiShop'
    | 'CiShoppingBasket'
    | 'CiShoppingCart'
    | 'CiShoppingTag'
    | 'CiShuffle'
    | 'CiSignpostDuo1'
    | 'CiSignpostL1'
    | 'CiSignpostR1'
    | 'CiSliderHorizontal'
    | 'CiSliderVertical'
    | 'CiSpeaker'
    | 'CiSquareAlert'
    | 'CiSquareCheck'
    | 'CiSquareChevDown'
    | 'CiSquareChevLeft'
    | 'CiSquareChevRight'
    | 'CiSquareChevUp'
    | 'CiSquareInfo'
    | 'CiSquareMinus'
    | 'CiSquareMore'
    | 'CiSquarePlus'
    | 'CiSquareQuestion'
    | 'CiSquareRemove'
    | 'CiStar'
    | 'CiStethoscope'
    | 'CiStickyNote'
    | 'CiStop1'
    | 'CiStopSign1'
    | 'CiStopwatch'
    | 'CiStreamOff'
    | 'CiStreamOn'
    | 'CiSun'
    | 'CiTablets1'
    | 'CiTempHigh'
    | 'CiText'
    | 'CiTextAlignCenter'
    | 'CiTextAlignJustify'
    | 'CiTextAlignLeft'
    | 'CiTextAlignRight'
    | 'CiTimer'
    | 'CiTrash'
    | 'CiTrophy'
    | 'CiTurnL1'
    | 'CiTurnR1'
    | 'CiTwitter'
    | 'CiUmbrella'
    | 'CiUndo'
    | 'CiUnlock'
    | 'CiUnread'
    | 'CiUsb'
    | 'CiUser'
    | 'CiVault'
    | 'CiVial'
    | 'CiVideoOff'
    | 'CiVideoOn'
    | 'CiViewBoard'
    | 'CiViewColumn'
    | 'CiViewList'
    | 'CiViewTable'
    | 'CiViewTimeline'
    | 'CiVirus'
    | 'CiVoicemail'
    | 'CiVolume'
    | 'CiVolumeHigh'
    | 'CiVolumeMute'
    | 'CiWallet'
    | 'CiWarning'
    | 'CiWavePulse1'
    | 'CiWheat'
    | 'CiWifiOff'
    | 'CiWifiOn'
    | 'CiYoutube'
    | 'CiZoomIn'
    | 'CiZoomOut'
    | 'HiAcademicCap'
    | 'HiAdjustments'
    | 'HiAnnotation'
    | 'HiArchive'
    | 'HiArrowCircleDown'
    | 'HiArrowCircleLeft'
    | 'HiArrowCircleRight'
    | 'HiArrowCircleUp'
    | 'HiArrowDown'
    | 'HiArrowLeft'
    | 'HiArrowNarrowDown'
    | 'HiArrowNarrowLeft'
    | 'HiArrowNarrowRight'
    | 'HiArrowNarrowUp'
    | 'HiArrowRight'
    | 'HiArrowSmDown'
    | 'HiArrowSmLeft'
    | 'HiArrowSmRight'
    | 'HiArrowSmUp'
    | 'HiArrowUp'
    | 'HiArrowsExpand'
    | 'HiAtSymbol'
    | 'HiBackspace'
    | 'HiBadgeCheck'
    | 'HiBan'
    | 'HiBeaker'
    | 'HiBell'
    | 'HiBookOpen'
    | 'HiBookmark'
    | 'HiBookmarkAlt'
    | 'HiBriefcase'
    | 'HiCake'
    | 'HiCalculator'
    | 'HiCalendar'
    | 'HiCamera'
    | 'HiCash'
    | 'HiChartBar'
    | 'HiChartPie'
    | 'HiChartSquareBar'
    | 'HiChat'
    | 'HiChatAlt'
    | 'HiChatAlt2'
    | 'HiCheck'
    | 'HiCheckCircle'
    | 'HiChevronDoubleDown'
    | 'HiChevronDoubleLeft'
    | 'HiChevronDoubleRight'
    | 'HiChevronDoubleUp'
    | 'HiChevronDown'
    | 'HiChevronLeft'
    | 'HiChevronRight'
    | 'HiChevronUp'
    | 'HiChip'
    | 'HiClipboard'
    | 'HiClipboardCheck'
    | 'HiClipboardCopy'
    | 'HiClipboardList'
    | 'HiClock'
    | 'HiCloud'
    | 'HiCloudDownload'
    | 'HiCloudUpload'
    | 'HiCode'
    | 'HiCog'
    | 'HiCollection'
    | 'HiColorSwatch'
    | 'HiCreditCard'
    | 'HiCube'
    | 'HiCubeTransparent'
    | 'HiCurrencyBangladeshi'
    | 'HiCurrencyDollar'
    | 'HiCurrencyEuro'
    | 'HiCurrencyPound'
    | 'HiCurrencyRupee'
    | 'HiCurrencyYen'
    | 'HiCursorClick'
    | 'HiDatabase'
    | 'HiDesktopComputer'
    | 'HiDeviceMobile'
    | 'HiDeviceTablet'
    | 'HiDocument'
    | 'HiDocumentAdd'
    | 'HiDocumentDownload'
    | 'HiDocumentDuplicate'
    | 'HiDocumentRemove'
    | 'HiDocumentReport'
    | 'HiDocumentSearch'
    | 'HiDocumentText'
    | 'HiDotsCircleHorizontal'
    | 'HiDotsHorizontal'
    | 'HiDotsVertical'
    | 'HiDownload'
    | 'HiDuplicate'
    | 'HiEmojiHappy'
    | 'HiEmojiSad'
    | 'HiExclamation'
    | 'HiExclamationCircle'
    | 'HiExternalLink'
    | 'HiEye'
    | 'HiEyeOff'
    | 'HiFastForward'
    | 'HiFilm'
    | 'HiFilter'
    | 'HiFingerPrint'
    | 'HiFire'
    | 'HiFlag'
    | 'HiFolder'
    | 'HiFolderAdd'
    | 'HiFolderDownload'
    | 'HiFolderOpen'
    | 'HiFolderRemove'
    | 'HiGift'
    | 'HiGlobe'
    | 'HiGlobeAlt'
    | 'HiHand'
    | 'HiHashtag'
    | 'HiHeart'
    | 'HiHome'
    | 'HiIdentification'
    | 'HiInbox'
    | 'HiInboxIn'
    | 'HiInformationCircle'
    | 'HiKey'
    | 'HiLibrary'
    | 'HiLightBulb'
    | 'HiLightningBolt'
    | 'HiLink'
    | 'HiLocationMarker'
    | 'HiLockClosed'
    | 'HiLockOpen'
    | 'HiLogin'
    | 'HiLogout'
    | 'HiMail'
    | 'HiMailOpen'
    | 'HiMap'
    | 'HiMenu'
    | 'HiMenuAlt1'
    | 'HiMenuAlt2'
    | 'HiMenuAlt3'
    | 'HiMenuAlt4'
    | 'HiMicrophone'
    | 'HiMinus'
    | 'HiMinusCircle'
    | 'HiMinusSm'
    | 'HiMoon'
    | 'HiMusicNote'
    | 'HiNewspaper'
    | 'HiOfficeBuilding'
    | 'HiOutlineAcademicCap'
    | 'HiOutlineAdjustments'
    | 'HiOutlineAnnotation'
    | 'HiOutlineArchive'
    | 'HiOutlineArrowCircleDown'
    | 'HiOutlineArrowCircleLeft'
    | 'HiOutlineArrowCircleRight'
    | 'HiOutlineArrowCircleUp'
    | 'HiOutlineArrowDown'
    | 'HiOutlineArrowLeft'
    | 'HiOutlineArrowNarrowDown'
    | 'HiOutlineArrowNarrowLeft'
    | 'HiOutlineArrowNarrowRight'
    | 'HiOutlineArrowNarrowUp'
    | 'HiOutlineArrowRight'
    | 'HiOutlineArrowSmDown'
    | 'HiOutlineArrowSmLeft'
    | 'HiOutlineArrowSmRight'
    | 'HiOutlineArrowSmUp'
    | 'HiOutlineArrowUp'
    | 'HiOutlineArrowsExpand'
    | 'HiOutlineAtSymbol'
    | 'HiOutlineBackspace'
    | 'HiOutlineBadgeCheck'
    | 'HiOutlineBan'
    | 'HiOutlineBeaker'
    | 'HiOutlineBell'
    | 'HiOutlineBookOpen'
    | 'HiOutlineBookmark'
    | 'HiOutlineBookmarkAlt'
    | 'HiOutlineBriefcase'
    | 'HiOutlineCake'
    | 'HiOutlineCalculator'
    | 'HiOutlineCalendar'
    | 'HiOutlineCamera'
    | 'HiOutlineCash'
    | 'HiOutlineChartBar'
    | 'HiOutlineChartPie'
    | 'HiOutlineChartSquareBar'
    | 'HiOutlineChat'
    | 'HiOutlineChatAlt'
    | 'HiOutlineChatAlt2'
    | 'HiOutlineCheck'
    | 'HiOutlineCheckCircle'
    | 'HiOutlineChevronDoubleDown'
    | 'HiOutlineChevronDoubleLeft'
    | 'HiOutlineChevronDoubleRight'
    | 'HiOutlineChevronDoubleUp'
    | 'HiOutlineChevronDown'
    | 'HiOutlineChevronLeft'
    | 'HiOutlineChevronRight'
    | 'HiOutlineChevronUp'
    | 'HiOutlineChip'
    | 'HiOutlineClipboard'
    | 'HiOutlineClipboardCheck'
    | 'HiOutlineClipboardCopy'
    | 'HiOutlineClipboardList'
    | 'HiOutlineClock'
    | 'HiOutlineCloud'
    | 'HiOutlineCloudDownload'
    | 'HiOutlineCloudUpload'
    | 'HiOutlineCode'
    | 'HiOutlineCog'
    | 'HiOutlineCollection'
    | 'HiOutlineColorSwatch'
    | 'HiOutlineCreditCard'
    | 'HiOutlineCube'
    | 'HiOutlineCubeTransparent'
    | 'HiOutlineCurrencyBangladeshi'
    | 'HiOutlineCurrencyDollar'
    | 'HiOutlineCurrencyEuro'
    | 'HiOutlineCurrencyPound'
    | 'HiOutlineCurrencyRupee'
    | 'HiOutlineCurrencyYen'
    | 'HiOutlineCursorClick'
    | 'HiOutlineDatabase'
    | 'HiOutlineDesktopComputer'
    | 'HiOutlineDeviceMobile'
    | 'HiOutlineDeviceTablet'
    | 'HiOutlineDocument'
    | 'HiOutlineDocumentAdd'
    | 'HiOutlineDocumentDownload'
    | 'HiOutlineDocumentDuplicate'
    | 'HiOutlineDocumentRemove'
    | 'HiOutlineDocumentReport'
    | 'HiOutlineDocumentSearch'
    | 'HiOutlineDocumentText'
    | 'HiOutlineDotsCircleHorizontal'
    | 'HiOutlineDotsHorizontal'
    | 'HiOutlineDotsVertical'
    | 'HiOutlineDownload'
    | 'HiOutlineDuplicate'
    | 'HiOutlineEmojiHappy'
    | 'HiOutlineEmojiSad'
    | 'HiOutlineExclamation'
    | 'HiOutlineExclamationCircle'
    | 'HiOutlineExternalLink'
    | 'HiOutlineEye'
    | 'HiOutlineEyeOff'
    | 'HiOutlineFastForward'
    | 'HiOutlineFilm'
    | 'HiOutlineFilter'
    | 'HiOutlineFingerPrint'
    | 'HiOutlineFire'
    | 'HiOutlineFlag'
    | 'HiOutlineFolder'
    | 'HiOutlineFolderAdd'
    | 'HiOutlineFolderDownload'
    | 'HiOutlineFolderOpen'
    | 'HiOutlineFolderRemove'
    | 'HiOutlineGift'
    | 'HiOutlineGlobe'
    | 'HiOutlineGlobeAlt'
    | 'HiOutlineHand'
    | 'HiOutlineHashtag'
    | 'HiOutlineHeart'
    | 'HiOutlineHome'
    | 'HiOutlineIdentification'
    | 'HiOutlineInbox'
    | 'HiOutlineInboxIn'
    | 'HiOutlineInformationCircle'
    | 'HiOutlineKey'
    | 'HiOutlineLibrary'
    | 'HiOutlineLightBulb'
    | 'HiOutlineLightningBolt'
    | 'HiOutlineLink'
    | 'HiOutlineLocationMarker'
    | 'HiOutlineLockClosed'
    | 'HiOutlineLockOpen'
    | 'HiOutlineLogin'
    | 'HiOutlineLogout'
    | 'HiOutlineMail'
    | 'HiOutlineMailOpen'
    | 'HiOutlineMap'
    | 'HiOutlineMenu'
    | 'HiOutlineMenuAlt1'
    | 'HiOutlineMenuAlt2'
    | 'HiOutlineMenuAlt3'
    | 'HiOutlineMenuAlt4'
    | 'HiOutlineMicrophone'
    | 'HiOutlineMinus'
    | 'HiOutlineMinusCircle'
    | 'HiOutlineMinusSm'
    | 'HiOutlineMoon'
    | 'HiOutlineMusicNote'
    | 'HiOutlineNewspaper'
    | 'HiOutlineOfficeBuilding'
    | 'HiOutlinePaperAirplane'
    | 'HiOutlinePaperClip'
    | 'HiOutlinePause'
    | 'HiOutlinePencil'
    | 'HiOutlinePencilAlt'
    | 'HiOutlinePhone'
    | 'HiOutlinePhoneIncoming'
    | 'HiOutlinePhoneMissedCall'
    | 'HiOutlinePhoneOutgoing'
    | 'HiOutlinePhotograph'
    | 'HiOutlinePlay'
    | 'HiOutlinePlus'
    | 'HiOutlinePlusCircle'
    | 'HiOutlinePlusSm'
    | 'HiOutlinePresentationChartBar'
    | 'HiOutlinePresentationChartLine'
    | 'HiOutlinePrinter'
    | 'HiOutlinePuzzle'
    | 'HiOutlineQrcode'
    | 'HiOutlineQuestionMarkCircle'
    | 'HiOutlineReceiptRefund'
    | 'HiOutlineReceiptTax'
    | 'HiOutlineRefresh'
    | 'HiOutlineReply'
    | 'HiOutlineRewind'
    | 'HiOutlineRss'
    | 'HiOutlineSave'
    | 'HiOutlineSaveAs'
    | 'HiOutlineScale'
    | 'HiOutlineScissors'
    | 'HiOutlineSearch'
    | 'HiOutlineSearchCircle'
    | 'HiOutlineSelector'
    | 'HiOutlineServer'
    | 'HiOutlineShare'
    | 'HiOutlineShieldCheck'
    | 'HiOutlineShieldExclamation'
    | 'HiOutlineShoppingBag'
    | 'HiOutlineShoppingCart'
    | 'HiOutlineSortAscending'
    | 'HiOutlineSortDescending'
    | 'HiOutlineSparkles'
    | 'HiOutlineSpeakerphone'
    | 'HiOutlineStar'
    | 'HiOutlineStatusOffline'
    | 'HiOutlineStatusOnline'
    | 'HiOutlineStop'
    | 'HiOutlineSun'
    | 'HiOutlineSupport'
    | 'HiOutlineSwitchHorizontal'
    | 'HiOutlineSwitchVertical'
    | 'HiOutlineTable'
    | 'HiOutlineTag'
    | 'HiOutlineTemplate'
    | 'HiOutlineTerminal'
    | 'HiOutlineThumbDown'
    | 'HiOutlineThumbUp'
    | 'HiOutlineTicket'
    | 'HiOutlineTranslate'
    | 'HiOutlineTrash'
    | 'HiOutlineTrendingDown'
    | 'HiOutlineTrendingUp'
    | 'HiOutlineTruck'
    | 'HiOutlineUpload'
    | 'HiOutlineUser'
    | 'HiOutlineUserAdd'
    | 'HiOutlineUserCircle'
    | 'HiOutlineUserGroup'
    | 'HiOutlineUserRemove'
    | 'HiOutlineUsers'
    | 'HiOutlineVariable'
    | 'HiOutlineVideoCamera'
    | 'HiOutlineViewBoards'
    | 'HiOutlineViewGrid'
    | 'HiOutlineViewGridAdd'
    | 'HiOutlineViewList'
    | 'HiOutlineVolumeOff'
    | 'HiOutlineVolumeUp'
    | 'HiOutlineWifi'
    | 'HiOutlineX'
    | 'HiOutlineXCircle'
    | 'HiOutlineZoomIn'
    | 'HiOutlineZoomOut'
    | 'HiPaperAirplane'
    | 'HiPaperClip'
    | 'HiPause'
    | 'HiPencil'
    | 'HiPencilAlt'
    | 'HiPhone'
    | 'HiPhoneIncoming'
    | 'HiPhoneMissedCall'
    | 'HiPhoneOutgoing'
    | 'HiPhotograph'
    | 'HiPlay'
    | 'HiPlus'
    | 'HiPlusCircle'
    | 'HiPlusSm'
    | 'HiPresentationChartBar'
    | 'HiPresentationChartLine'
    | 'HiPrinter'
    | 'HiPuzzle'
    | 'HiQrcode'
    | 'HiQuestionMarkCircle'
    | 'HiReceiptRefund'
    | 'HiReceiptTax'
    | 'HiRefresh'
    | 'HiReply'
    | 'HiRewind'
    | 'HiRss'
    | 'HiSave'
    | 'HiSaveAs'
    | 'HiScale'
    | 'HiScissors'
    | 'HiSearch'
    | 'HiSearchCircle'
    | 'HiSelector'
    | 'HiServer'
    | 'HiShare'
    | 'HiShieldCheck'
    | 'HiShieldExclamation'
    | 'HiShoppingBag'
    | 'HiShoppingCart'
    | 'HiSortAscending'
    | 'HiSortDescending'
    | 'HiSparkles'
    | 'HiSpeakerphone'
    | 'HiStar'
    | 'HiStatusOffline'
    | 'HiStatusOnline'
    | 'HiStop'
    | 'HiSun'
    | 'HiSupport'
    | 'HiSwitchHorizontal'
    | 'HiSwitchVertical'
    | 'HiTable'
    | 'HiTag'
    | 'HiTemplate'
    | 'HiTerminal'
    | 'HiThumbDown'
    | 'HiThumbUp'
    | 'HiTicket'
    | 'HiTranslate'
    | 'HiTrash'
    | 'HiTrendingDown'
    | 'HiTrendingUp'
    | 'HiTruck'
    | 'HiUpload'
    | 'HiUser'
    | 'HiUserAdd'
    | 'HiUserCircle'
    | 'HiUserGroup'
    | 'HiUserRemove'
    | 'HiUsers'
    | 'HiVariable'
    | 'HiVideoCamera'
    | 'HiViewBoards'
    | 'HiViewGrid'
    | 'HiViewGridAdd'
    | 'HiViewList'
    | 'HiVolumeOff'
    | 'HiVolumeUp'
    | 'HiWifi'
    | 'HiX'
    | 'HiXCircle'
    | 'HiZoomIn'
    | 'HiZoomOut';
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToActionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlock".
 */
export interface GridBlock {
  columns: '1' | '2' | '3' | '4';
  gap?: ('small' | 'medium' | 'large') | null;
  blocks: (
    | BannerBlock
    | MediaBlock
    | FormBlock
    | SearchBlock
    | ProductCardBlock
    | RecommendationBlock
    | SloganBlock
    | TitleBlock
    | TrendingTagsBlock
    | CallToActionBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock".
 */
export interface RowBlock {
  alignment?: ('start' | 'center' | 'end' | 'between') | null;
  verticalAlignment?: ('start' | 'center' | 'end') | null;
  blocks: (
    | BannerBlock
    | MediaBlock
    | FormBlock
    | SearchBlock
    | ProductCardBlock
    | RecommendationBlock
    | SloganBlock
    | TitleBlock
    | TrendingTagsBlock
    | CallToActionBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'rowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  totalAmount?: number | null;
  status: 'pending' | 'unpaid' | 'unshipped' | 'shipped' | 'confirmed' | 'refunding' | 'refunded';
  quantity?: {
    Adult?: number | null;
    Youth?: number | null;
    Children?: number | null;
    Senior?: number | null;
  };
  ticket: string | ProductOption;
  product: string | Product;
  date: string;
  time: string;
  email?: string | null;
  requiredInfo?:
    | {
        info: {
          name: string;
          value?:
            | {
                field: {
                  key: string;
                  value: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  paypalOrderId?: string | null;
  paymentDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-search".
 */
export interface PostSearch {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  categories?:
    | {
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-search".
 */
export interface CitySearch {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'cities';
    value: string | City;
  };
  categories?:
    | {
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'product-options';
        value: string | ProductOption;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-fields';
        value: string | OrderField;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'product-search';
        value: string | ProductSearch;
      } | null)
    | ({
        relationTo: 'post-search';
        value: string | PostSearch;
      } | null)
    | ({
        relationTo: 'city-search';
        value: string | CitySearch;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hideSearchInput?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        columnBlock?: T | ColumnBlockSelect<T>;
        gridBlock?: T | GridBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        bannerBlock?: T | BannerBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        searchBlock?: T | SearchBlockSelect<T>;
        productCardBlock?: T | ProductCardBlockSelect<T>;
        recommendationBlock?: T | RecommendationBlockSelect<T>;
        sloganBlock?: T | SloganBlockSelect<T>;
        titleBlock?: T | TitleBlockSelect<T>;
        trendingTagsBlock?: T | TrendingTagsBlockSelect<T>;
        callToActionBlock?: T | CallToActionBlockSelect<T>;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  meta?:
    | T
    | {
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnBlock_select".
 */
export interface ColumnBlockSelect<T extends boolean = true> {
  alignment?: T;
  spacing?: T;
  blocks?:
    | T
    | {
        bannerBlock?: T | BannerBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        searchBlock?: T | SearchBlockSelect<T>;
        productCardBlock?: T | ProductCardBlockSelect<T>;
        recommendationBlock?: T | RecommendationBlockSelect<T>;
        sloganBlock?: T | SloganBlockSelect<T>;
        titleBlock?: T | TitleBlockSelect<T>;
        trendingTagsBlock?: T | TrendingTagsBlockSelect<T>;
        callToActionBlock?: T | CallToActionBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SearchBlock_select".
 */
export interface SearchBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  placeholder?: T;
  trendingSearches?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCardBlock_select".
 */
export interface ProductCardBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendationBlock_select".
 */
export interface RecommendationBlockSelect<T extends boolean = true> {
  mode?: T;
  selectedProducts?: T;
  filterType?: T;
  city?: T;
  category?: T;
  limit?: T;
  enableLoadMore?: T;
  loadMoreLimit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sloganBlock_select".
 */
export interface SloganBlockSelect<T extends boolean = true> {
  keywords?:
    | T
    | {
        text?: T;
        isLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "titleBlock_select".
 */
export interface TitleBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  variant?: T;
  color?: T;
  size?: T;
  textTransform?: T;
  weight?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trendingTagsBlock_select".
 */
export interface TrendingTagsBlockSelect<T extends boolean = true> {
  tags?:
    | T
    | {
        text?: T;
        isLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  buttonText?: T;
  icon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlock_select".
 */
export interface GridBlockSelect<T extends boolean = true> {
  columns?: T;
  gap?: T;
  blocks?:
    | T
    | {
        bannerBlock?: T | BannerBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        searchBlock?: T | SearchBlockSelect<T>;
        productCardBlock?: T | ProductCardBlockSelect<T>;
        recommendationBlock?: T | RecommendationBlockSelect<T>;
        sloganBlock?: T | SloganBlockSelect<T>;
        titleBlock?: T | TitleBlockSelect<T>;
        trendingTagsBlock?: T | TrendingTagsBlockSelect<T>;
        callToActionBlock?: T | CallToActionBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock_select".
 */
export interface RowBlockSelect<T extends boolean = true> {
  alignment?: T;
  verticalAlignment?: T;
  blocks?:
    | T
    | {
        bannerBlock?: T | BannerBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        searchBlock?: T | SearchBlockSelect<T>;
        productCardBlock?: T | ProductCardBlockSelect<T>;
        recommendationBlock?: T | RecommendationBlockSelect<T>;
        sloganBlock?: T | SloganBlockSelect<T>;
        titleBlock?: T | TitleBlockSelect<T>;
        trendingTagsBlock?: T | TrendingTagsBlockSelect<T>;
        callToActionBlock?: T | CallToActionBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  meta?:
    | T
    | {
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  lowestPrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  categories?: T;
  summary?: T;
  aboutThisTour?:
    | T
    | {
        cancellation?: T;
        duration?: T;
        disabledFriendly?: T;
        skipTicketLine?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  importantInfo?:
    | T
    | {
        title?: T;
        content?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  city?: T;
  productOptions?: T;
  slug?: T;
  slugLock?: T;
  meta?:
    | T
    | {
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  themeColor?: T;
  slug?: T;
  slugLock?: T;
  meta?:
    | T
    | {
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-options_select".
 */
export interface ProductOptionsSelect<T extends boolean = true> {
  useAsTitle?: T;
  product?: T;
  title?: T;
  summary?: T;
  applicableCustomers?: T;
  requiredInfo?: T;
  availableDate?:
    | T
    | {
        months?: T;
        days?: T;
        available?: T;
        timeRange?:
          | T
          | {
              time?: T;
              id?: T;
            };
        price?:
          | T
          | {
              Adult?: T;
              Youth?: T;
              Children?: T;
              Senior?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  totalAmount?: T;
  status?: T;
  quantity?:
    | T
    | {
        Adult?: T;
        Youth?: T;
        Children?: T;
        Senior?: T;
      };
  ticket?: T;
  product?: T;
  date?: T;
  time?: T;
  email?: T;
  requiredInfo?:
    | T
    | {
        info?:
          | T
          | {
              name?: T;
              value?:
                | T
                | {
                    field?:
                      | T
                      | {
                          key?: T;
                          value?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  paypalOrderId?: T;
  paymentDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-fields_select".
 */
export interface OrderFieldsSelect<T extends boolean = true> {
  name?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        payment?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-search_select".
 */
export interface ProductSearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  categories?:
    | T
    | {
        id?: T;
        title?: T;
      };
  summary?: T;
  image?:
    | T
    | {
        url?: T;
        alt?: T;
      };
  slug?: T;
  city?:
    | T
    | {
        title?: T;
        themeColor?: T;
      };
  aboutThisTour?:
    | T
    | {
        cancellation?: T;
        duration?: T;
        disabledFriendly?: T;
        skipTicketLine?: T;
      };
  lowestPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-search_select".
 */
export interface PostSearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  categories?:
    | T
    | {
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-search_select".
 */
export interface CitySearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  categories?:
    | T
    | {
        id?: T;
        title?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'cities';
                value: string | City;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'cities';
                value: string | City;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          /**
           * 选择链接的样式
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}